[features]
seeds = true
skip-lint = false

[programs.localnet]
proposal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
resolution = "resL1j3p3QXAD2oQWW14Uv18iJrfoAwrCd3qTd2QDyj"
vote_hook_interface = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nprince/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
